//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TouristGuide.WP7.WPService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attraction", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class Attraction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TouristGuide.WP7.WPService.Address AddressField;
        
        private TouristGuide.WP7.WPService.AttractionType AttractionTypeField;
        
        private System.Nullable<double> AvgRatingField;
        
        private TouristGuide.WP7.WPService.Coordinates CoordinatesField;
        
        private TouristGuide.WP7.WPService.Country CountryField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.AttractionImage> ImagesField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.AttractionReview> ReviewsField;
        
        private string VideoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.AttractionType AttractionType {
            get {
                return this.AttractionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttractionTypeField, value) != true)) {
                    this.AttractionTypeField = value;
                    this.RaisePropertyChanged("AttractionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> AvgRating {
            get {
                return this.AvgRatingField;
            }
            set {
                if ((this.AvgRatingField.Equals(value) != true)) {
                    this.AvgRatingField = value;
                    this.RaisePropertyChanged("AvgRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.Coordinates Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.AttractionImage> Images {
            get {
                return this.ImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagesField, value) != true)) {
                    this.ImagesField = value;
                    this.RaisePropertyChanged("Images");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.AttractionReview> Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Video {
            get {
                return this.VideoField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoField, value) != true)) {
                    this.VideoField = value;
                    this.RaisePropertyChanged("Video");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> BuildingNumberField;
        
        private string CityField;
        
        private TouristGuide.WP7.WPService.Country CountryField;
        
        private int IDField;
        
        private string RegionField;
        
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((this.BuildingNumberField.Equals(value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.Country Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttractionType", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class AttractionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinates", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class Coordinates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TouristGuide.WP7.WPService.Coordinates CoordinatesField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TouristGuide.WP7.WPService.Coordinates Coordinates {
            get {
                return this.CoordinatesField;
            }
            set {
                if ((object.ReferenceEquals(this.CoordinatesField, value) != true)) {
                    this.CoordinatesField = value;
                    this.RaisePropertyChanged("Coordinates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttractionImage", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class AttractionImage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AttractionIDField;
        
        private string FileNameField;
        
        private int IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttractionID {
            get {
                return this.AttractionIDField;
            }
            set {
                if ((this.AttractionIDField.Equals(value) != true)) {
                    this.AttractionIDField = value;
                    this.RaisePropertyChanged("AttractionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttractionReview", Namespace="http://schemas.datacontract.org/2004/07/TouristGuide.Core.Models")]
    public partial class AttractionReview : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AttractionIDField;
        
        private string AuthorField;
        
        private System.DateTime DateField;
        
        private int IDField;
        
        private int RatingField;
        
        private string TextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttractionID {
            get {
                return this.AttractionIDField;
            }
            set {
                if ((this.AttractionIDField.Equals(value) != true)) {
                    this.AttractionIDField = value;
                    this.RaisePropertyChanged("AttractionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WPService.IWPService")]
    public interface IWPService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWPService/GetAttractions", ReplyAction="http://tempuri.org/IWPService/GetAttractionsResponse")]
        System.IAsyncResult BeginGetAttractions(string place, int start, int count, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> EndGetAttractions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWPService/SearchAttractions", ReplyAction="http://tempuri.org/IWPService/SearchAttractionsResponse")]
        System.IAsyncResult BeginSearchAttractions(string inputText, int start, int count, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> EndSearchAttractions(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWPService/GetAttractionById", ReplyAction="http://tempuri.org/IWPService/GetAttractionByIdResponse")]
        System.IAsyncResult BeginGetAttractionById(int id, System.AsyncCallback callback, object asyncState);
        
        TouristGuide.WP7.WPService.Attraction EndGetAttractionById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWPServiceChannel : TouristGuide.WP7.WPService.IWPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAttractionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAttractionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchAttractionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchAttractionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAttractionByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAttractionByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TouristGuide.WP7.WPService.Attraction Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TouristGuide.WP7.WPService.Attraction)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WPServiceClient : System.ServiceModel.ClientBase<TouristGuide.WP7.WPService.IWPService>, TouristGuide.WP7.WPService.IWPService {
        
        private BeginOperationDelegate onBeginGetAttractionsDelegate;
        
        private EndOperationDelegate onEndGetAttractionsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAttractionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchAttractionsDelegate;
        
        private EndOperationDelegate onEndSearchAttractionsDelegate;
        
        private System.Threading.SendOrPostCallback onSearchAttractionsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAttractionByIdDelegate;
        
        private EndOperationDelegate onEndGetAttractionByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetAttractionByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WPServiceClient() {
        }
        
        public WPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAttractionsCompletedEventArgs> GetAttractionsCompleted;
        
        public event System.EventHandler<SearchAttractionsCompletedEventArgs> SearchAttractionsCompleted;
        
        public event System.EventHandler<GetAttractionByIdCompletedEventArgs> GetAttractionByIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TouristGuide.WP7.WPService.IWPService.BeginGetAttractions(string place, int start, int count, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAttractions(place, start, count, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> TouristGuide.WP7.WPService.IWPService.EndGetAttractions(System.IAsyncResult result) {
            return base.Channel.EndGetAttractions(result);
        }
        
        private System.IAsyncResult OnBeginGetAttractions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string place = ((string)(inValues[0]));
            int start = ((int)(inValues[1]));
            int count = ((int)(inValues[2]));
            return ((TouristGuide.WP7.WPService.IWPService)(this)).BeginGetAttractions(place, start, count, callback, asyncState);
        }
        
        private object[] OnEndGetAttractions(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> retVal = ((TouristGuide.WP7.WPService.IWPService)(this)).EndGetAttractions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAttractionsCompleted(object state) {
            if ((this.GetAttractionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAttractionsCompleted(this, new GetAttractionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAttractionsAsync(string place, int start, int count) {
            this.GetAttractionsAsync(place, start, count, null);
        }
        
        public void GetAttractionsAsync(string place, int start, int count, object userState) {
            if ((this.onBeginGetAttractionsDelegate == null)) {
                this.onBeginGetAttractionsDelegate = new BeginOperationDelegate(this.OnBeginGetAttractions);
            }
            if ((this.onEndGetAttractionsDelegate == null)) {
                this.onEndGetAttractionsDelegate = new EndOperationDelegate(this.OnEndGetAttractions);
            }
            if ((this.onGetAttractionsCompletedDelegate == null)) {
                this.onGetAttractionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAttractionsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAttractionsDelegate, new object[] {
                        place,
                        start,
                        count}, this.onEndGetAttractionsDelegate, this.onGetAttractionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TouristGuide.WP7.WPService.IWPService.BeginSearchAttractions(string inputText, int start, int count, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearchAttractions(inputText, start, count, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> TouristGuide.WP7.WPService.IWPService.EndSearchAttractions(System.IAsyncResult result) {
            return base.Channel.EndSearchAttractions(result);
        }
        
        private System.IAsyncResult OnBeginSearchAttractions(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string inputText = ((string)(inValues[0]));
            int start = ((int)(inValues[1]));
            int count = ((int)(inValues[2]));
            return ((TouristGuide.WP7.WPService.IWPService)(this)).BeginSearchAttractions(inputText, start, count, callback, asyncState);
        }
        
        private object[] OnEndSearchAttractions(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> retVal = ((TouristGuide.WP7.WPService.IWPService)(this)).EndSearchAttractions(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchAttractionsCompleted(object state) {
            if ((this.SearchAttractionsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchAttractionsCompleted(this, new SearchAttractionsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAttractionsAsync(string inputText, int start, int count) {
            this.SearchAttractionsAsync(inputText, start, count, null);
        }
        
        public void SearchAttractionsAsync(string inputText, int start, int count, object userState) {
            if ((this.onBeginSearchAttractionsDelegate == null)) {
                this.onBeginSearchAttractionsDelegate = new BeginOperationDelegate(this.OnBeginSearchAttractions);
            }
            if ((this.onEndSearchAttractionsDelegate == null)) {
                this.onEndSearchAttractionsDelegate = new EndOperationDelegate(this.OnEndSearchAttractions);
            }
            if ((this.onSearchAttractionsCompletedDelegate == null)) {
                this.onSearchAttractionsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchAttractionsCompleted);
            }
            base.InvokeAsync(this.onBeginSearchAttractionsDelegate, new object[] {
                        inputText,
                        start,
                        count}, this.onEndSearchAttractionsDelegate, this.onSearchAttractionsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TouristGuide.WP7.WPService.IWPService.BeginGetAttractionById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAttractionById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TouristGuide.WP7.WPService.Attraction TouristGuide.WP7.WPService.IWPService.EndGetAttractionById(System.IAsyncResult result) {
            return base.Channel.EndGetAttractionById(result);
        }
        
        private System.IAsyncResult OnBeginGetAttractionById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((TouristGuide.WP7.WPService.IWPService)(this)).BeginGetAttractionById(id, callback, asyncState);
        }
        
        private object[] OnEndGetAttractionById(System.IAsyncResult result) {
            TouristGuide.WP7.WPService.Attraction retVal = ((TouristGuide.WP7.WPService.IWPService)(this)).EndGetAttractionById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAttractionByIdCompleted(object state) {
            if ((this.GetAttractionByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAttractionByIdCompleted(this, new GetAttractionByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAttractionByIdAsync(int id) {
            this.GetAttractionByIdAsync(id, null);
        }
        
        public void GetAttractionByIdAsync(int id, object userState) {
            if ((this.onBeginGetAttractionByIdDelegate == null)) {
                this.onBeginGetAttractionByIdDelegate = new BeginOperationDelegate(this.OnBeginGetAttractionById);
            }
            if ((this.onEndGetAttractionByIdDelegate == null)) {
                this.onEndGetAttractionByIdDelegate = new EndOperationDelegate(this.OnEndGetAttractionById);
            }
            if ((this.onGetAttractionByIdCompletedDelegate == null)) {
                this.onGetAttractionByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAttractionByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetAttractionByIdDelegate, new object[] {
                        id}, this.onEndGetAttractionByIdDelegate, this.onGetAttractionByIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TouristGuide.WP7.WPService.IWPService CreateChannel() {
            return new WPServiceClientChannel(this);
        }
        
        private class WPServiceClientChannel : ChannelBase<TouristGuide.WP7.WPService.IWPService>, TouristGuide.WP7.WPService.IWPService {
            
            public WPServiceClientChannel(System.ServiceModel.ClientBase<TouristGuide.WP7.WPService.IWPService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAttractions(string place, int start, int count, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = place;
                _args[1] = start;
                _args[2] = count;
                System.IAsyncResult _result = base.BeginInvoke("GetAttractions", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> EndGetAttractions(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> _result = ((System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction>)(base.EndInvoke("GetAttractions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearchAttractions(string inputText, int start, int count, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = inputText;
                _args[1] = start;
                _args[2] = count;
                System.IAsyncResult _result = base.BeginInvoke("SearchAttractions", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> EndSearchAttractions(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction> _result = ((System.Collections.ObjectModel.ObservableCollection<TouristGuide.WP7.WPService.Attraction>)(base.EndInvoke("SearchAttractions", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAttractionById(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetAttractionById", _args, callback, asyncState);
                return _result;
            }
            
            public TouristGuide.WP7.WPService.Attraction EndGetAttractionById(System.IAsyncResult result) {
                object[] _args = new object[0];
                TouristGuide.WP7.WPService.Attraction _result = ((TouristGuide.WP7.WPService.Attraction)(base.EndInvoke("GetAttractionById", _args, result)));
                return _result;
            }
        }
    }
}
